#!/usr/bin/env ruby

require 'rbconfig'
STDERR.puts "DEBUG: ruby prefix: #{RbConfig::CONFIG['prefix']}"

require 'rubygems'
require 'tempfile'
require 'fileutils'
require 'json'

module CupsFilter
  class Job
    attr_reader :job_id, :user, :title, :copies, :options, :source
    def initialize(*argv)
      @job_id, @user, @title, @copies, @options, @source = *argv
    end

    def read
      if @source
        File.open(@source, 'rb', &:read)
      else
        STDIN.read
      end
    end

    def tmpInput
      File.open("/tmp/rawimg-backend-#{$$}.tmp.#{@job_id}", 'wb') { |fp| fp << self.read }
    end
  end
end

# passthru - let backend do the lifting

job = CupsFilter::Job.new(*ARGV)

STDOUT.write(job.read)

